#!/bin/sh
# Edit this if you want a different prompter.
PROMPT="dmenu -l 15 -i -p"
REMCOMMENT=

verify_email () {
    IN=$(cat /dev/stdin)
    echo "$IN" | grep -q '@' && echo "$IN" && return 0
    echo "$IN Not an email." >/dev/stderr ; return 1
}

mail_addrs () {
    sed 's/[\\t ]*#.*//' "$XDG_CONFIG_HOME"/prompt-mail.conf \
        | xargs sed -E "s/^alias[\\t ]+[a-zA-Z0-9]+[ \\t]+// ; s/[ \\t]+$//" \
        | sed -E "s:~:$HOME:g" \
        | sort \
        | uniq
}

mail_addrs \
    | $PROMPT 'mail address:' \
    | sed  's/ *#.*//' \
    | verify_email
