#!/bin/sh
# edit this if you want a different prompter.
PROMPT="dmenu -i -p"

verify_email () {
    IN=$(cat /dev/stdin)
    echo "$IN" | grep -q '@' && echo "$IN" && return 0
    echo "$IN Not an email." >/dev/stderr ; return 1
}

mail_addrs () {
    cat ~/.config/prompt-mail.conf  \
        | sed 's/^#.*$//' \
        | xargs sed -E 's/^alias +[a-zA-Z0-9]+ // ; s/#.*$//'
}

mail_addrs \
    | $PROMPT 'mail address:' \
    | verify_email
